game_modes = {
    "Wipeout": "Aniquilación",
    "Siege": "Asedio",
    "Heist": "Atraco",
    "Gem Grab": "Atrapagemas",
    "Brawl Ball": "Balón Brawl",
    "Basket Brawl": "Basketbrawl",
    "Bot Drop": "Bowdrop",
    "Bounty": "Caza Estelar",
    "Unknown": "Desconocido",
    "Duels": "Duelo",
    "Big Game": "Gran_Juego",
    "Hold The Trophy": "Hold The Throphy",
    "Hunters": "Hunters",
    "Trophy Thieves": "Ladrones Trofeos",
    "Lone Star": "Lone Star",
    "Knockout": "Noqueo",
    "Payload": "Payload",
    "Boss Fight": "Pelea de Jefe",
    "Present Plunder": "Present Plunder",
    "Robo Rumble": "Robo Rumble",
    "Snowtel Thieves": "Snowtel Thieves",
    "Super City Rampage": "Super City Rampage",
    "Duo Showdown": "Supervivencia Duo",
    "Solo Showdown": "Supervivencia Solo",
    "Takedown": "Takedown",
    "Last Stand": "Último en Pie",
    "Volley Brawl": "Volleybrawl",
    "Hot Zone": "Zona Restringida",
    "wipeout": "Aniquilación",
    "siege": "Asedio",
    "heist": "Atraco",
    "gemGrab": "Atrapagemas",
    "brawlBall": "Balón Brawl",
    "basketBrawl": "Basketbrawl",
    "botDrop": "Bowdrop",
    "bounty": "Caza Estelar",
    "unknown": "Desconocido",
    "duels": "Duelo",
    "bigGame": "Gran_Juego",
    "holdTheTrophy": "Hold The Throphy",
    "hunters": "Hunters",
    "trophyThieves": "Ladrones Trofeos",
    "loneStar": "Lone Star",
    "knockout": "Noqueo",
    "payload": "Payload",
    "bossFight": "Pelea de Jefe",
    "presentPlunder": "Present Plunder",
    "roboRumble": "Robo Rumble",
    "snowtelThieves": "Snowtel Thieves",
    "superCityRampage": "Super City Rampage",
    "duoShowdown": "Supervivencia Duo",
    "soloShowdown": "Supervivencia Solo",
    "takedown": "Takedown",
    "lastStand": "Último en Pie",
    "volleyBrawl": "Volleybrawl",
    "hotZone": "Zona Restringida",
}
